version: "3.7"
services:
  go-grpc:
    build:
      context: ./go-grpc/
      dockerfile: Dockerfile
    container_name: "go-grpc"
    platform: linux/amd64
    volumes:
      - ../../:/go-grpc
    tty: true
    privileged: true